version: 2
jobs:
  build:
    docker:
      - image: debian:stretch-slim
    steps:
      - checkout
      - run: apt-get update -qq && apt-get install -qq cloc make wget luacheck  luajit lua5.1 lua5.2 lua5.3
      - run: make ci
