version: 2.1

orbs:
  windows: circleci/windows@2.2.0

jobs:
  build:
    docker:
      - image: debian:testing
    steps:
      - checkout
      - run:
          command: |
            apt-get update -qq && apt-get install -qq cloc make lua-check \
              luajit lua5.1 lua5.2 lua5.3 lua5.4
      - run: make ci
  windows:
    executor: windows/default
    steps:
      - checkout
      - run: choco install lua53
      - run: choco install make
      - run: make test LUA=lua53

workflows:
  version: 2
  all:
    jobs:
      - build
      - windows
